server:
  port: 80
spring:
  application:
    name: cloud-order-servie

eureka:
  client:
    # 注册进入eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka