server:
  port: 8006
spring:
  application:
    name: cousul-provider-payment

  cloud:
    # cousel 注册地址
    consul:
      host: localhost
      port: 8500
      discovery:
        # 服务名称
        service-name: ${spring.application.name}

# 下载consul  mac环境
  # 下载url；https://www.consul.io/downloads.html
  # 使用的homebrew 下载  `brew install consul`, 下载比较慢，需等待
  # 启动测试环境  `consul agent -dev`
  # 访问web 页面  http://localhost:8500/ui/dc1/services