server:
  port: 80
spring:
  application:
    name: clous-consumer-order

  cloud:
    # cousel 注册地址
    consul:
      host: localhost
      port: 8500
      discovery:
        # 服务名称
        service-name: ${spring.application.name}