server:
  port: 9527

spring:
  application:
    name: cloud-order-servie
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                 # 开启从注册中心动态创建路由的功能。理由微服务名进行路由
      routes:
        - id: payment_routh               # 路由的ID，没有固定的规则但要求唯一
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # cloud-payment-service 表示注册中心提供服务的名称
          predicates:
            - Path=/payment/get/**        # 断言路由低配的进行路由

        - id: payment_routh2              # 路由的ID，没有固定的规则但要求唯一
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # cloud-payment-service 表示注册中心提供服务的名称
          predicates:
            - Path=/payment/lb/**        # 断言路由低配的进行路由
            # - After=2020-06-27T19:35:05.565496+08:00[Asia/Shanghai] # 标识在这个时间之后，才可以匹配到这个路由信息
            # - Before=2020-06-27T19:35:05.565496+08:00[Asia/Shanghai]  # 标识在这个时间之前，才可以匹配到这个路由
            # - Between=2020-06-27T18:35:05.565496+08:00[Asia/Shanghai], 2020-06-28T19:35:05.565496+08:00[Asia/Shanghai] # 标识需要在这个连个时间点之间的，才可以匹配到这个路由
            # - Cookie=username,sevensecond # 标识Cookie里面必需是有一个username，值是sevensecond的时候，才匹配到路由，注意：Cookie值其实可以是一个正则表达式,curl http://localhost:9527/payment/lb --cookie "username=sevensecond"
            # - Host=**.seven.second.com # 标识host标识必需**.seven.second.com才可以匹配到
            - Header=X-Request-id, \d+  # header 里面必需有个X-Request-id，并且值是个正整数
            - Method=GET    # Method 必需是get请求
            - Query=id, \d+ # 请求参数是username，值是正整数才可以  #curl http://localhost:9527/payment/lb\?id\=12 -H "X-Request-id:20"

eureka:
  client:
    # 注册进入eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka