server:
  port: 9527

spring:
  application:
    name: cloud-order-servie
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                 # 开启从注册中心动态创建路由的功能。理由微服务名进行路由
      routes:
        - id: payment_routh               # 路由的ID，没有固定的规则但要求唯一
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # cloud-payment-service 表示注册中心提供服务的名称
          predicates:
            - Path=/payment/ /**        # 断言路由低配的进行路由

        - id: payment_routh2              # 路由的ID，没有固定的规则但要求唯一
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # cloud-payment-service 表示注册中心提供服务的名称
          predicates:
            - Path=/payment/lb/**        # 断言路由低配的进行路由

eureka:
  client:
    # 注册进入eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka