server:
  port: 9001
spring:
  application:
    name: provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"



# nacos 官网：https://nacos.io/en-us/
# nacos 文档：https://nacos.io/zh-cn/docs/what-is-nacos.html
# nacos 下载地址：https://github.com/alibaba/nacos/releases/tag/1.3.0

# 我是用的是docker下载
# docker pull nacos/nacos-server
# docker run --env MODE=standalone --name nacos -d -p 8848:8848 nacos/nacos-server


# 安装完成后，浏览器：http://localhost:8848/nacos,就可以看到地址

