server:
  port: 83

spring:
  application:
    name: consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719


# fegin 允许服务降级使用
feign:
  sentinel:
    enabled: true
