server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      # zookeeper 地址
      connect-string: localhost:2181


# 启动zookeeper
  # 1.进入到zookeeper的bin目录
    # 启动：zkServer.sh start
    # 暂停 zkServer.sh stop
  # 2.进入zeekeeper
    # ./zkCli.sh
  # 3.查看zeekeeper，上面的服务
    # ls /
  # 4.查看服务上面的服务提供者
    # ls /services